setopt no_beep
setopt prompt_subst
setopt rc_quotes
setopt auto_cd
setopt multios
setopt long_list_jobs
setopt auto_resume
setopt notify
setopt complete_in_word
setopt extended_glob
setopt always_to_end
setopt path_dirs

setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_reduce_blanks
setopt inc_append_history_time
setopt extended_history

unsetopt share_history
unsetopt append_history
unsetopt flow_control
unsetopt menu_complete
unsetopt case_glob
